name: productsapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.2.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_login: ^5.0.0
  shared_preferences: ^2.2.2
  quickalert: ^1.1.0
  get: ^4.6.6
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# flutter icon existing
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/myprod.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:

  uses-material-design: true

  # assets:
  #   - assets/images/basic.png

  fonts:
    - family: SometypeMono
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf




